---
# yamllint disable rule:line-length
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: osshelp/drone-linter
    failure: ignore

  - name: build-backend
    image: plugins/docker
    settings:
      dockerfile: backend/Dockerfile.no-buildkit
      context: backend
      repo: 0xb1b1/misis-cjsc-backend-lct-yakutia-2023
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      status: [success, changed]
      event:
        - push
      branch:
        - main
        # yamllint disable-line rule:anchors
        - "backend-master"

  - name: build-vk-bot
    image: plugins/docker
    settings:
      dockerfile: vk-bot/Dockerfile.no-buildkit
      context: vk-bot
      repo: 0xb1b1/misis-cjsc-vk-bot-lct-yakutia-2023
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      status: [success, changed]
      event:
        - push
      branch:
        - main
        # yamllint disable-line rule:anchors
        - "vk-bot-master"

  # - name: build-ml
  #   image: plugins/docker
  #   settings:
  #     dockerfile: ml/Dockerfile.no-buildkit
  #     context: ml
  #     repo: 0xb1b1/misis-cjsc-ml-lct-yakutia-2023
  #     tags: latest
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  #   when:
  #     status: [success, changed]
  #     event:
  #       - push
  #     branch:
  #       - main
  #       # yamllint disable-line rule:anchors
  #       - "ml-master"

  - name: build_notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: build_notif_discord_id
      webhook_token:
        from_secret: build_notif_discord_token
      message: >
        {{#success build.status}}
          # 🦄 Build successful
        {{else}}
          # 💩 Build failed
        {{/success}}
        Repository `[{{repo.name}}/{{commit.branch}}]`
        triggered by event `[{{uppercase build.event}}]` for build.

        ## Git

          - Commit [[{{commit.sha}}]({{commit.link}})]
          - Author `[{{commit.author}} / {{commit.email}}]`
          - Message: {{commit.message}}

        ## Drone CI

          - Build [[#{{build.number}}]({{build.link}})]
          - Reported `[{{uppercase build.status}}]` at `[{{datetime build.finished "2006.01.02 15:04" ""}}]`
    when:
      status: [success, failure, changed]
      event:
        - push
      branch:
        - main
        # yamllint disable-line rule:anchors
        - "*-master"
    depends_on:
      - build-backend
      - build-vk-bot
